algoritmo name
    início
        literal letra 

        escreva("Digite uma letra: ")
        leia(letra)

        escolha(letra){
            caso "a":
            caso "e":
            caso "i":
            caso "o":
            caso "u":
                escreva("Você digitou uma vogal")
            pare
            padrao:
                escreva("Você digitou uma consoante")
        }
    fim